name: Simple S3 Upload
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug secret availability
        run: |
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID is available"
          else
            echo "AWS_ACCESS_KEY_ID is missing"
          fi
          if [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS_SECRET_ACCESS_KEY is available"
          else
            echo "AWS_SECRET_ACCESS_KEY is missing"
          fi

      - name: Deploy to S3 using jakejarvis/s3-sync-action
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: myawsmigrate1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '.'
