name: Debug AWS Credentials
on:
  push:
    branches:
      - main
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Secrets
        run: |
          echo "Checking if GitHub secrets exist:"
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID secret exists"
          else
            echo "AWS_ACCESS_KEY_ID secret is missing or empty"
          fi
          
          if [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS_SECRET_ACCESS_KEY secret exists"
          else
            echo "AWS_SECRET_ACCESS_KEY secret is missing or empty"
          fi
          
          if [ -n "${{ secrets.AWS_REGION }}" ]; then
            echo "AWS_REGION secret exists"
          else
            echo "AWS_REGION secret is missing or empty"
          fi
          
      - name: Check if secrets can be assigned to environment variables
        env:
          KEY_TEST: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_TEST: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION_TEST: ${{ secrets.AWS_REGION }}
        run: |
          echo "Testing environment variable assignment:"
          if [ -n "$KEY_TEST" ]; then
            echo "Successfully assigned AWS_ACCESS_KEY_ID to environment variable"
          else
            echo "Failed to assign AWS_ACCESS_KEY_ID to environment variable"
          fi
          
          if [ -n "$SECRET_TEST" ]; then
            echo "Successfully assigned AWS_SECRET_ACCESS_KEY to environment variable"
          else
            echo "Failed to assign AWS_SECRET_ACCESS_KEY to environment variable"
          fi
          
          if [ -n "$REGION_TEST" ]; then
            echo "Successfully assigned AWS_REGION to environment variable"
          else
            echo "Failed to assign AWS_REGION to environment variable"
          fi
      
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version
      
      - name: Verify AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Attempting to validate AWS credentials by calling AWS API:"
          if aws sts get-caller-identity; then
            echo "✅ AWS credentials are valid and working"
            echo "AWS Account ID: $(aws sts get-caller-identity --query 'Account' --output text)"
            echo "AWS User ARN: $(aws sts get-caller-identity --query 'Arn' --output text)"
          else
            echo "❌ AWS credentials validation failed. Please check your credentials."
          fi
