name: Debug AWS Credentials
on:
  push:
    branches:
      - main
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Secrets
        run: |
          echo "Checking if GitHub secrets exist:"
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID secret exists"
          else
            echo "AWS_ACCESS_KEY_ID secret is missing or empty"
          fi
          
          if [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS_SECRET_ACCESS_KEY secret exists"
          else
            echo "AWS_SECRET_ACCESS_KEY secret is missing or empty"
          fi
          
      - name: Check if secrets can be seen directly
        env:
          KEY_TEST: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_TEST: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Testing environment variable assignment:"
          if [ -n "$KEY_TEST" ]; then
            echo "Successfully assigned AWS_ACCESS_KEY_ID to environment variable"
          else
            echo "Failed to assign AWS_ACCESS_KEY_ID to environment variable"
          fi
          
          if [ -n "$SECRET_TEST" ]; then
            echo "Successfully assigned AWS_SECRET_ACCESS_KEY to environment variable"
          else
            echo "Failed to assign AWS_SECRET_ACCESS_KEY to environment variable"
          fi
