name: Migrate GitHub Repository to S3

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering

jobs:
  migrate-to-s3:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install AWS CLI
      run: |
        pip install awscli
    
    - name: Verify AWS credentials
      run: |
        echo "Checking if AWS credentials exist:"
        if [ -n "$AWS_ACCESS_KEY" ]; then
          echo "✅ AWS_ACCESS_KEY secret exists"
        else
          echo "❌ AWS_ACCESS_KEY secret is missing or empty"
          exit 1
        fi
        if [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "✅ AWS_SECRET_ACCESS_KEY secret exists"
        else
          echo "❌ AWS_SECRET_ACCESS_KEY secret is missing or empty"
          exit 1
        fi
        if [ -n "$AWS_REGION" ]; then
          echo "✅ AWS_REGION secret exists"
        else
          echo "❌ AWS_REGION secret is missing or empty"
          exit 1
        fi
        if [ -n "$AWS_S3_BUCKET" ]; then
          echo "✅ AWS_S3_BUCKET secret exists"
        else
          echo "❌ AWS_S3_BUCKET secret is missing or empty"
          exit 1
        fi
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    
    - name: Set up AWS CLI credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Compute File Integrity Checksums
      run: |
        echo "Generating file checksums before upload..."
        find . -type f -not -path "./.git/*" -not -path "./node_modules/*" -exec sha256sum {} + > checksums.txt
        aws s3 cp checksums.txt s3://myawsmigrate1/checksums.txt
        echo "✅ Uploaded file checksums to S3."

    - name: Upload files to S3 maintaining folder structure
      run: |
        echo "Uploading repository contents to s3://myawsmigrate1/..."
        aws s3 cp . s3://myawsmigrate1/ --recursive --exclude ".git/*" --exclude "node_modules/*"
        echo "✅ Successfully uploaded repository contents to s3://myawsmigrate1/"

    - name: Create repository metadata file
      run: |
        REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        METADATA_FILE="metadata-${TIMESTAMP}.json"
        
        echo '{' > $METADATA_FILE
        echo "  \"repository\": \"$GITHUB_REPOSITORY\"," >> $METADATA_FILE
        echo "  \"branch\": \"${GITHUB_REF#refs/heads/}\"," >> $METADATA_FILE
        echo "  \"commit\": \"$GITHUB_SHA\"," >> $METADATA_FILE
        echo "  \"migrationDate\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"," >> $METADATA_FILE
        echo "  \"migrationBy\": \"$GITHUB_ACTOR\"" >> $METADATA_FILE
        echo '}' >> $METADATA_FILE
        
        aws s3 cp "${METADATA_FILE}" "s3://myawsmigrate1/${METADATA_FILE}"
        echo "✅ Successfully uploaded metadata to s3://myawsmigrate1/${METADATA_FILE}"

    - name: Upload Workflow Logs to S3
      if: always()
      run: |
        mkdir logs
        cp $GITHUB_WORKSPACE/.github/workflows/migrate-to-s3.yml logs/
        cp $GITHUB_WORKSPACE/.github/workflows/* logs/ || true
        aws s3 cp logs/ s3://myawsmigrate1/logs/ --recursive
        echo "✅ Successfully uploaded workflow logs to S3."

    - name: Send Slack Notification
      if: always()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        STATUS="✅ Migration Succeeded"
        if [ "$GITHUB_JOB_STATUS" != "success" ]; then
          STATUS="❌ Migration Failed"
        fi
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$STATUS: Repository ${GITHUB_REPOSITORY} was migrated to S3.\nBranch: ${GITHUB_REF#refs/heads/}\nCommit: $GITHUB_SHA\nTriggered by: $GITHUB_ACTOR\"}" $SLACK_WEBHOOK_URL
